Module2 task1
htmlacademy-adaptive/610981-mishka-26 pull request #2
Opened 2022-07-31 12:44 UTC by jdoroshina

2022-07-31 15:05 UTC, firefoxic commented on source/index.html
> +					</blockquote>
Шаблонизатор очень добрый и за тебя фиксит (поэтому валидатор не ругнулся) этот задублировавшийся закрывающий `</blockquote>` 😊

Но давай и в исходнике поправим это.

2022-07-31 19:35 UTC, firefoxic requested changes

2022-07-31 19:35 UTC, firefoxic commented on source/index.html
> +					</blockquote>
Шаблонизатор очень добрый и за тебя фиксит (поэтому валидатор не ругнулся) этот задублировавшийся закрывающий </blockquote> 😊

Но давай и в исходнике поправим это.

2022-07-31 19:35 UTC, firefoxic commented on source/index.html
> +		<h2 class="visually-hidden">Популярные разделы каталога.</h2>
В заголовках точки не ставят 🤫

2022-07-31 19:35 UTC, firefoxic commented on source/index.html
> +	</section>
А зачем тут `section`? 🤔

2022-07-31 19:35 UTC, firefoxic commented on source/catalog.html
> +						<span class="visually-hidden">В корзину.</span>
Кажется понял. Точки в каждом `visually-hidden`. Этого не нужно. Точни нужны только в `alt` изображений.

2022-07-31 19:35 UTC, firefoxic commented on source/catalog.html
> +		</video>
Видео у нас не будет. Будет место под него занятое превьюшкой для видео. Поверх неё кнопкоссылка, по нажатию на которую без js переходим на страницу видео (может на ютуб), а с js скрипт подменяет превьюху на видео (или айфрейм с ютуба).

2022-07-31 19:35 UTC, firefoxic commented on source/templates/modal.twig
> +						</label>
1. У группы радиокнопок одинаковыей `name` должны быть.
2. Если собираешься иконками оформлять, то спаны лишние нам не понадобятся, только для скрытия текста. А вообще вроде и текстом нормально стилизуются эти контролы.

2022-07-31 19:35 UTC, firefoxic commented on source/templates/header.twig
> +	<a class="page-header__logo">
`href="./index.html"` нужен

2022-07-31 19:35 UTC, firefoxic commented on source/templates/footer.twig
> +			<span class="visually-hidden">Логотип «Html Academy».</span>
Достаточно просто «Html Academy. Мы же не изображение описываем, а указано кем разработано.

2022-08-01 04:27 UTC, jdoroshina commented on source/catalog.html
> +						<span class="visually-hidden">В корзину.</span>
Да, нас в прошлом модуле обязали так сделать. В критериях это было) а нескольких студентов разворачивали обратно при проверке на защите без точек в visually-hidden
Я так понимаю, что раз этот заголовок сделан для читалок, то точка в конце ставится для более правильной интонации в конце. Ведь это фактически же как  alt.
Или раз мы в видимых заголовках точке не ставим, то и тут не надо?

2022-08-01 04:34 UTC, jdoroshina commented on source/templates/footer.twig
> +			<span class="visually-hidden">Логотип «Html Academy».</span>
А в этой ситуации тоже не поняла :( Потому что весь прошлый модуль мы скрытыми span подписывали svg в разметке (как alt) если у него не было текстового пояснения. Например, иконка корзины в каталоге Глейси подписывалась "Добавить в корзину"

2022-08-01 04:44 UTC, jdoroshina commented on source/index.html
> +	</section>
Вообще тут должен быть <header> заменю)

2022-08-01 05:52 UTC, firefoxic commented on source/index.html
> +	</section>
А должен быть?
Можно же просто заголовок оставить.

2022-08-01 05:54 UTC, firefoxic commented on source/catalog.html
> +						<span class="visually-hidden">В корзину.</span>
Я уже зарепортил авторам, что это бессмысленно (репорт перерос в долгое обсуждение). Надеюсь к следующему потоку 1 курса поправят. А на 2 курсе критерии старые, в них нет этого.

2022-08-01 07:54 UTC, merged